# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10acbbdd9bef2e628f14d142b0e3ef42086289236c6c11e967100f3bb600f2b8c57232070942a6918994dbb097dd6de797970b09bdc33830816d3a16666e43ac

test:
  secret_key_base: 31bc7673caa2915e6f791e779d7cfe019d5943bb091d405bcda02900c9ae16c05e777a3cb3682d3035102bb79a848b40587a3b7e8db5fe4bb1c87dd4d6d30c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
